### ISSUE TITLE
[TPS loader] Make TPS loader input more flexible

### ISSUE THREAD

**Issue by janezpodhostnik** [onflow/flow-go#5490]
## Problem Definition

TPS loader input is not detailed enough.

Currently you start the loader like this: 
```
go run ../benchmark/cmd/ci -log-level info -git-repo-path ../../ -tps-initial 800 -tps-min 1 -tps-max 1200 -duration 30m -load-type "token-tranfer"
```

The automated job can currently change the load type but not any other parameters.

This causes issues with loads where an initial starting TPS of 800 is way to much and it breaks the whole run.
This is also an issue if we would like to specify extra parameters for any load type (e.i.: "create-account" load type could receive a parameter on how many accounts to create per transaction)

## Proposed Solution

The input to the command could be a json or yaml file path, which would then be parsed into the parameters needed for that run.

```yaml
name: "token transfer"
run_parameters:
  max_tps: 1200
  min_tps: 1
  initial_tps: 800
  duration: 30m
load_parameters:
  transfers_per_transaction: 1
```

## Definition of Done

- [ ] The TPS automated loader can use different load types where each load type specifies its own parameters
